title: Yuchen Tang's Blog
description: 乱七八糟种种

theme: null

markdown: kramdown

# Valine
# You can get your appid and appkey from https://leancloud.app
# more info please open https://valine.js.org

valine_comment:
  enable: true
  appid: vMyJmm66vLDlv5NhBWsf72ak-MdYXbMMI
  appkey: N7XcLbK23w0Kv67lzK3zNS5z
  placeholder: "Comment Here"

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
